[package]
name = "graphrox-c"
authors.workspace = true
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

[lib]
doc = false
name = "graphrox"
crate-type = ["cdylib"]

[dependencies]
graphrox = { path = "../graphrox-rs" }
