[workspace]

members = [
    "graphrox-rs",
    "graphrox-c",
]

[workspace.package]
authors = ["Tanner Davies"]
version = "1.2.0"
edition = "2021"
description = "A graph library for graph compression and fast processing of graph approximations"
license = "MIT"