[workspace]

members = [
    "graphrox-rs",
    "graphrox-c",
]

[workspace.package]
authors = ["Tanner Davies"]
version = "0.1.0"
edition = "2021"
description = "A graph library for fast processing of graph approximations"
license = "MIT"